author: Andy Huang (huang_a @ chiisana.net)
database: false
main: net.chiisana.builddit.Builddit
name: Builddit
startup: postworld
url: http://mc.chiisana.net/
version: '1.0'

commands:
  builddit:
    description: generate schematic download link for plot you're standing on.